Feature/typeorm setting
MI-ON/mion pull request #7
Opened 2021-08-04 13:58 UTC by nayoon030303

2021-08-04 15:03 UTC, julianne03 requested changes

2021-08-04 15:03 UTC, julianne03 commented on server/src/index.ts
> +createConnection().then(async connection => {
제가 찾아보니까 ormconfig.json에 있는 비밀번호 같이 중요한 정보들을 따로 ts 파일로 빼서 ormconfig.json 대신 connection config로 불러올 수 있더라고요! 여기 블로그 링크 남기니 참고해보세요!!

https://seogenie2.tistory.com/5

2021-08-04 15:03 UTC, julianne03 commented on server/src/entity/User.ts
> +    image: Blob;
오! 제가 말하려고 했던 부분을 딱 고쳐주셨네요..짱!!!! 😆

2021-08-04 15:04 UTC, julianne03 approved these changes

2021-08-04 18:08 UTC, nayoon030303 commented on server/src/index.ts
> +createConnection().then(async connection => {
config.ts파일로 변경했습니다. 
.env 파일은 ignore했기 때문에 따로 전송해드리겠습니다.

2021-08-04 18:08 UTC, merged

2021-08-05 02:00 UTC, julianne03 commented on server/src/index.ts
> +createConnection().then(async connection => {
고생하셨네요ㅜㅜ 😭